version: "3"

services:
  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=xudjf23adj213
    ports:
      - 3306:3306

  java-demo:
    build:
      context: ./java-spring-boot
    ports:
      - 8080:8080

  rust-demo:
    build:
      context: ./spring-rs
    ports:
      - 8080:8080