version: "3"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=xudjf23adj213
    ports:
      - 5432:5432

  java-demo:
    image: holmofy/java-spring-boot-demo-pg:0.0.1
    build:
      context: ./java-spring-boot
    ports:
      - 80:8080
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 1024M

  rust-demo:
    image: holmofy/rust-spring-rs-demo-pg:0.0.1
    build:
      context: ./spring-rs
    ports:
      - 88:8080
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 80M