[package]
name = "spring-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
spring = "0.0.8"
spring-web = "0.0.8"
spring-sqlx = { version = "0.0.8", features = ["mysql"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
