[package]
name = "spring-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spring-rs"
path = "src/main.rs"

[dependencies]
spring = "0.0.9"
spring-web = "0.0.9"
spring-sqlx = { version = "0.0.9", features = ["postgres"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
